name: violence-detection-env
channels:
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - asttokens=2.0.5=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - ca-certificates=2022.07.19=h06a4308_0
  - certifi=2022.6.15=py39h06a4308_0
  - debugpy=1.5.1=py39h295c915_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - executing=0.8.3=pyhd3eb1b0_0
  - ipykernel=6.9.1=py39h06a4308_0
  - ipython=8.1.1=py39h06a4308_0
  - jedi=0.18.1=py39h06a4308_1
  - jupyter_client=6.1.7=py_0
  - jupyter_core=4.9.2=py39h06a4308_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgomp=9.3.0=h5101ec6_17
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - ncurses=6.3=h7f8727e_2
  - openssl=1.1.1q=h7f8727e_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - python=3.9.7=h12debd9_1
  - pyzmq=22.3.0=py39h295c915_2
  - readline=8.1.2=h7f8727e_1
  - setuptools=58.0.4=py39h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.38.0=hc218d9a_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tk=8.6.11=h1ccaba5_0
  - tornado=6.1=py39h27cfd23_0
  - traitlets=5.1.1=pyhd3eb1b0_0
  - tzdata=2021e=hda174b7_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.4=h2531618_0
  - zlib=1.2.11=h7f8727e_4
  - pip:
    - absl-py==1.0.0
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - astunparse==1.6.3
    - attrs==21.4.0
    - beautifulsoup4==4.10.0
    - bleach==4.1.0
    - cachetools==5.0.0
    - cffi==1.15.0
    - charset-normalizer==2.0.12
    - cycler==0.11.0
    - defusedxml==0.7.1
    - entrypoints==0.4
    - flatbuffers==2.0
    - fonttools==4.31.2
    - gast==0.5.3
    - google-auth==2.6.2
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.44.0
    - h5py==3.6.0
    - idna==3.3
    - imageio==2.19.3
    - importlib-metadata==4.11.3
    - ipynbname==2021.3.2
    - ipython-genutils==0.2.0
    - ipywidgets==7.7.0
    - jinja2==3.1.1
    - joblib==1.1.0
    - jsonschema==4.4.0
    - jupyter==1.0.0
    - jupyter-client==7.2.0
    - jupyter-console==6.4.3
    - jupyterlab-pygments==0.1.2
    - jupyterlab-widgets==1.1.0
    - kaggle==1.5.12
    - keras==2.8.0
    - keras-preprocessing==1.1.2
    - kiwisolver==1.4.0
    - libclang==13.0.0
    - markdown==3.3.6
    - markupsafe==2.1.1
    - matplotlib==3.5.1
    - mistune==0.8.4
    - nbclient==0.5.13
    - nbconvert==6.4.5
    - nbformat==5.2.0
    - nest-asyncio==1.5.4
    - networkx==2.8.5
    - notebook==6.4.10
    - numpy==1.22.3
    - oauthlib==3.2.0
    - opencv-python==4.5.5.64
    - opt-einsum==3.3.0
    - packaging==21.3
    - pandas==1.4.1
    - pandocfilters==1.5.0
    - pillow==9.0.1
    - pip==22.0.4
    - prometheus-client==0.13.1
    - protobuf==3.19.4
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.21
    - pyparsing==3.0.7
    - pypng==0.0.21
    - pyrsistent==0.18.1
    - python-dateutil==2.8.2
    - python-slugify==6.1.1
    - pytz==2022.1
    - pywavelets==1.3.0
    - qtconsole==5.3.0
    - qtpy==2.0.1
    - requests==2.27.1
    - requests-oauthlib==1.3.1
    - rsa==4.8
    - scikit-image==0.19.3
    - scikit-learn==1.0.2
    - scipy==1.8.0
    - seaborn==0.11.2
    - send2trash==1.8.0
    - soupsieve==2.3.1
    - style==1.1.0
    - tensorboard==2.8.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow==2.8.0
    - tensorflow-io-gcs-filesystem==0.24.0
    - termcolor==1.1.0
    - terminado==0.13.3
    - testpath==0.6.0
    - text-unidecode==1.3
    - tf-estimator-nightly==2.8.0.dev2021122109
    - tf-slim==1.1.0
    - threadpoolctl==3.1.0
    - tifffile==2022.5.4
    - torch==1.11.0+cu113
    - torchaudio==0.11.0+cu113
    - torchvision==0.12.0+cu113
    - tqdm==4.63.1
    - typing-extensions==4.1.1
    - urllib3==1.26.9
    - webencodings==0.5.1
    - werkzeug==2.0.3
    - widgetsnbextension==3.6.0
    - wrapt==1.14.0
    - zipp==3.7.0
prefix: /home/atmguille/miniconda3/envs/violence-detection-env
